### ISSUE TITLE
Can't encode character exception on Windows

### ISSUE THREAD

**Issue by timokoessler** [opengrep/opengrep#17]
**Describe the bug**
Opengrep crashes on Windows with the following error:

```
Traceback (most recent call last):
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u23eb' in position 60: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Scripts\pysemgrep.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\semgrep\console_scripts\pysemgrep.py", line 52, in main
    sys.exit(semgrep.main.main())
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\semgrep\main.py", line 120, in main
    cli(prog_name="semgrep")
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\semgrep\commands\wrapper.py", line 37, in wrapper
    func(*args, **kwargs)
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\semgrep\commands\scan.py", line 891, in scan
    version_check()
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\semgrep\app\version.py", line 239, in version_check
    _show_banners()
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\semgrep\app\version.py", line 221, in _show_banners
    logger.warning(f"\n{icon} {message}")
Message: '\n⏫ A new version of Semgrep is available. See https://semgrep.dev/docs/upgrading'
Arguments: ()

✨ If Semgrep missed a finding, please send us feedback to let us know!
   See https://semgrep.dev/docs/reporting-false-negatives/
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2728' in position 59: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Scripts\pysemgrep.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\semgrep\console_scripts\pysemgrep.py", line 52, in main
    sys.exit(semgrep.main.main())
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\semgrep\main.py", line 120, in main
    cli(prog_name="semgrep")
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\semgrep\commands\wrapper.py", line 37, in wrapper
    func(*args, **kwargs)
  File "C:\Users\info\.version-fox\cache\python\v-3.12.3\python-3.12.3\Lib\site-packages\semgrep\commands\scan.py", line 897, in scan
    logger.info(msg)
Message: '\n✨ If Semgrep missed a finding, please send us feedback to let us know!\n   See \x1b[36m\x1b[22m\x1b[4mhttps://semgrep.dev/docs/reporting-false-negatives/\x1b[0m'
Arguments: ()
```

**To Reproduce**
Run `semgrep scan --config <path> -j 1 <path>`

**Expected behavior**
Opengrep should not crash.

**Environment**
Windows 11, Python 3.12.3

**Comment by Kirill89** [comment]
This issue seems to be very similar to https://github.com/Delgan/loguru/issues/124

TL;DR: It may not be a bug. Setting an environment variable `export PYTHONIOENCODING=UTF-8` should solve the problem.

**Comment by timokoessler** [comment]
Thanks! I tried this, but I still get the same exception. I checked the stdin/stdout encoding using `sys.stdout.encoding` and it's already utf-8 by default. Also the env var is ignored by default now (see https://docs.python.org/3/using/cmdline.html#envvar-PYTHONIOENCODING). Additionally setting `PYTHONLEGACYWINDOWSSTDIO` does not help.

**Comment by dimitris-m** [comment]
The problem might be that it's trying to read a file which has been checked out in the default Windows encoding, which may not be UTF-8 (even if this is also supported).

**Comment by timokoessler** [comment]
The error is not happening anymore with the latest opengrep build (with the same files) 😅. The config and the scanned js file are both utf8. Only getting `Invalid_argument: Unix.setitimer not implemented` now.

**Comment by willem-delbare** [comment]
fixed in latest windows build

**Comment by dimitris-m** [comment]
So it seems the pyinstaller binary works fine, but the wheel fails.
